### PR TITLE
added new glasses for med and medsec hud. added special centcom glasses.

### PR DESCRIPTION
**Pull request by Creatorbot01**
Added medical glasses
Just like security glasses but using medical hud
Added medsec glasses
both medical and security hud but now with flash protection
Added Specialize NT glasses
Medical, Security and Diagnostic Borg Hud all in one with flash and weld protection. mostly for centcom agent.

### CODE REVIEW

**Comment by Creatorbot01** [comment]
you can blame the fail on missing content.replay

**Comment by bruhmogus** [comment]
most fails unrelated, fix rsi validation first

**Comment by Creatorbot01** [comment]
rsi fail aint even my fault this fork is fuckin missing the warden winter suit brah

**Comment by bruhmogus** [comment]
okay nevermind this is fine to merge, all test fails unrelated

**Pull request closed without merging**
